controller_frequency: 10.0
recovery_behavior_enabled: true
clearing_rotation_allowed: true

TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_rotational_vel: 1.0
  min_in_place_rotational_vel: 0.4
  acc_lim_th: 0.1
  acc_lim_x: 0.2
  acc_lim_y: 0.2
  holonomic_robot: true
  occdist_scale: 0.5
  pdist_scale: 1.5
  gdist_scale: 1.5